### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by QABoahene** [musikalkemist/spotifyplaylistgenerator#1]
Hey
First of all, great tutorial. I have been trying to follow it code by code but I get this error. 
```
    track in response_json["items"]]
KeyError: 'items'
```
Can you help? This is from the _spotifycleint.py_ and `get_last_played_tracks` function.

**Comment by adstokes** [comment]
@QABoahene your auth token used in the terminal may have expired, refresh the token and re run the code it should work

**Comment by QABoahene** [comment]
This error was due to a mistake with the token

**Comment by AtomicNess123** [comment]
I am having the same problem. How did you solve it?

**Comment by QABoahene** [comment]
This was because there weren't any items to be retrieved. You should check your spotify credentials and also export them before you can run all the code.

**Comment by AtomicNess123** [comment]
I have exported my credentials already (when I do  `echo $SPOTIFY_AUTHORIZATION_TOKEN`  and same for ID, I get the codes on the Terminal). What do you mean that there were any items?

**Comment by QABoahene** [comment]
The code is grabbing some information from the json file which will be the items. This issue happened because of the credentials for me. I had to redo the process to get my credentials again from the spotify API platform.

**Comment by AtomicNess123** [comment]
Thanks, in my case it is not the credentials, so I will have to investigate why.
